language: ruby
cache: bundler

before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y autoconf automake boost1.55 libffi-dev

before_script:
  - test `which zkServer.sh` && zkServer.sh stop && rm -rf /tmp/zookeeper/*; true
  - wget -q -O - "http://mirrors.koehn.com/apache/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz" | tar zx -C "$HOME/"
  - export PATH="$PATH:/$HOME/zookeeper-3.4.6/bin"
  - cp "$HOME/zookeeper-3.4.6/conf/zoo_sample.cfg" "$HOME/zookeeper-3.4.6/conf/zoo.cfg"
  - zkServer.sh start

rvm:
  - 2.1.5
  - 2.1.2
  - 2.2.0

jdk:
  - openjdk7

script: ZK_URL=localhost:2181 bundle exec rake
