language: ruby
cache: bundler

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y autoconf automake libboost1.55-dev libffi-dev
  - gem update bundler

rvm:
  - 2.3.1

script: bundle exec rake spec
services:
  - redis-server

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

after_success:
  - bundle exec codeclimate-test-reporter
