#!/usr/bin/env ruby

require 'yaml'

begin
    environment = ENV['ENVIRONMENT']
    if environment == nil
        environment = 'production'
    end

    databases = YAML.load(File.read("/production_config/database.yml"))
    db = databases[environment]

    PG_HOST = db['host']
    PG_PORT = db['port']
    PG_DB = db['database']
    PG_USER = db['user']
    PG_PASS = db['password']
rescue Errno::ENOENT
    PG_HOST = ENV['PG_PORT_5432_TCP_ADDR']
    PG_PORT = ENV['PG_PORT_5432_TCP_PORT']
    PG_DB = ENV['PG_ENV_DB']
    PG_USER = ENV['PG_ENV_PG_USER']
    PG_PASS = ENV['PG_ENV_PASS']
end

exit system(
    "ATTENTION_REDIS_URL=\"#{ ENV["REDIS_PORT_6379_TCP_ADDR"] }:6379/0\" \
    PG_HOST=#{PG_HOST} \
    PG_PORT=#{PG_PORT} \
    PG_DB=#{PG_DB} \
    PG_USER=#{PG_USER} \
    PG_PASS=#{PG_PASS} \
    puma"
)
